### ISSUE TITLE
Issues with responsive design

### ISSUE THREAD

**Issue by paranoidunicorn** [BrunnerLivio/Portfolio2#1]
There are some issues in the area of responsive design. 
Depending on the ratio between the height and width of the visitor's browser, the 'Contact' section becomes invisible and hides behind the 'Timeline' section. In addition to that, some anchors are wrongly placed.

**Comment by paranoidunicorn** [comment]
Issue still exists.

**Comment by BrunnerLivio** [comment]
@paranoidunicorn
Yes I know, thanks, but I'm currently starting with a version 2.0 and abandon 1.0. Thanks anyway :)
